# Generated by Django 4.2 on 2024-06-11 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Represents a migration object that includes information about a specific migration task.
    
        Class Attributes:
        - initial: Represents the initial state of the migration task.
        - dependencies: Represents a list of dependencies required for the migration task.
        - operations: Represents a list of operations to be executed during the migration task.
    """


    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyticity', models.FloatField(null=True)),
                ('leadership', models.IntegerField(null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
