# Generated by Django 5.0.4 on 2024-06-12 03:18

from django.db import migrations


class Migration(migrations.Migration):
    """
    A class representing a migration, which includes methods and attributes for database migration operations.
    
        Class Attributes:
        - dependencies: Represents the dependencies of the migration.
        - operations: Represents the operations to be executed during the migration.
    """


    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanalytics',
            old_name='student',
            new_name='student_id',
        ),
    ]
