# Generated by Django 5.0.4 on 2024-06-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This class represents a migration object that handles database schema migration tasks.
    
        Class Attributes:
        - dependencies: A list of other migration classes that this migration depends on.
        - operations: A list of database schema operations defined in this migration.
    
        The Migration class provides methods to execute and revert database schema operations during migration process.
    """


    dependencies = [
        ('analytics', '0002_rename_student_studentanalytics_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanalytics',
            name='analyticity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentanalytics',
            name='leadership',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentanalytics',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
