from rest_framework.views import exception_handler


def core_exception_handler(exc, context):
    """
    Handle exceptions by delegating to specific error handlers based on the exception type.

        This function processes an exception and its context, attempting to create a standardized response
        by invoking an appropriate handler if the exception type is recognized. If no specific handler is found,
        it returns a default response generated by the exception handler.

        Args:
            exc: The exception instance that has been raised.
            context: The context in which the exception was raised, providing additional information.

        Returns:
            A response object corresponding to the exception handling result, or None if no response is generated.
    """
    response = exception_handler(exc, context)
    handlers = {"ValidationError": _handle_generic_error}

    exception_class = exc.__class__.__name__

    if exception_class in handlers:
        return handlers[exception_class](exc, context, response)

    return response


def _handle_generic_error(exc, context, response):
    """
    Handles a generic error by modifying the response data.

        This method takes an exception, context, and a response object,
        and updates the response data to include the errors from the original
        response.

        Args:
            exc: The exception that was raised.
            context: The context in which the error occurred.
            response: The response object to be updated with error information.

        Returns:
            The modified response object containing the updated error data.
    """
    response.data = {"errors": response.data}

    return response
