# Generated by Django 4.2 on 2024-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Class representing a migration task to be executed on a database. 
    
        Class Attributes:
        - dependencies: List of other migration tasks that this task depends on.
        - operations: List of operations to be executed for the migration task.
    
        This class defines a migration task with dependencies and operations to be executed.
    """


    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='result',
            name='points_user',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
